apiVersion: v1
kind: Namespace
metadata:
  name: argo-cd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argo-cd
  namespace: kube-system
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  targetNamespace: argo-cd
  valuesContent: |-
    dex:
      enabled: false # disable external auth providers
    server:
      extraArgs:
      - --insecure
    server:
      service:
        type: LoadBalancer
        servicePortHttp: 8080
        servicePortHttps: 4433
    configs:
      params:
        "server.insecure": true
      cm:
        "admin.enabled": true
      secret:
        argocdServerAdminPassword: $2y$10$1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ # hashed admin password
      repositories:
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
